version: "3.9"

services:
  frontend:
    build: ./frontend
    environment:
      - API_URL=https://api.giftmatchwill.work/
    depends_on:
      - backend
    restart: always
    networks:
      - webnet
    labels:
      - "traefik.enable=true"
  #   HTTPS domínio
      - "traefik.http.routers.frontend.rule=Host(`giftmatchwill.work`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
  

  backend:
    build: ./backend
    environment:
      - SENDGRID_API_KEY_FILE=/run/secrets/sendgrid_api_key
    secrets:
      - sendgrid_api_key
    restart: always
    networks:
      - webnet
    expose:
      - "8000"
    labels:
      - traefik.enable=true
    
      # HTTPS API pública
      - traefik.http.routers.backend.rule=Host(`api.giftmatchwill.work`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=mytlschallenge
      - traefik.http.services.backend.loadbalancer.server.port=8000


      # HTTP local (IP)
      - "traefik.http.routers.backend-ip.rule=Host(`192.168.1.123`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-ip.entrypoints=web"
      - "traefik.http.routers.backend-ip.service=backend-ip"
      - "traefik.http.services.backend-ip.loadbalancer.server.port=8000"


  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--api.insecure=true"


      # entrypoints HTTP + HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Let's Encrypt
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=teuemail@exemplo.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

    networks:
      - webnet

    restart: always

secrets:
  sendgrid_api_key:
    file: ./secrets/sendgrid_api_key.txt

networks:
  webnet:
    driver: bridge
