version: "3.9"

services:
  frontend:
    build: ./frontend
    environment:
      - API_URL=https://api.giftmatchwill.work/
    depends_on:
      - backend
    restart: always
    networks:
      - webnet
    labels:
      - traefik.enable=true

      # HTTPS dom√≠nio via Cloudflare DNS-01
      - traefik.http.routers.frontend.rule=Host(`giftmatchwill.work`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=cloudflare
      - traefik.http.routers.frontend.tls=true
      - traefik.http.services.frontend.loadbalancer.server.port=80
      #- traefik.http.routers.frontend.service=frontend-svc
  



  backend:
    build: ./backend
    environment:
      - SENDGRID_API_KEY_FILE=/run/secrets/sendgrid_api_key
    secrets:
      - sendgrid_api_key
    restart: always
    networks:
      - webnet
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"

      # HTTPS API via Cloudflare DNS-01
      - "traefik.http.routers.backend.rule=Host(`api.giftmatchwill.work`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=cloudflare"
      - traefik.http.routers.backend.tls=true
      - traefik.http.services.backend-svc.loadbalancer.server.port=8000
      - traefik.http.routers.backend.service=backend-svc



  reverse-proxy:
    image: traefik:latest
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--api.dashboard=true"
      - "--api.debug=true"

      # entrypoints HTTP + HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Let's Encrypt via Cloudflare DNS-01
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=teuemail@exemplo.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

    networks:
      - webnet

    restart: always

secrets:
  sendgrid_api_key:
    file: ./secrets/sendgrid_api_key.txt

networks:
  webnet:
    driver: bridge
