apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amigo-secreto
  namespace: argocd   # namespace onde o Argo CD está instalado
spec:
  project: default
  source:
    repoURL: '/home/lfcaldeira/Code/amigo-secreto/k8s'  # caminho local para os manifests
    targetRevision: HEAD
    path: '.'  # todos os manifests no diretório
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true       # remove recursos que não existem mais no Git
      selfHeal: true    # aplica automaticamente mudanças no Git
