apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amigo-secreto
  namespace: argocd   # namespace onde o Argo CD está instalado
spec:
  project: default
  source:
    repoURL: 'https://github.com/lfcaldeira/amigo-secreto'
    targetRevision: HEAD
    path: 'k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true       # remove recursos que não existem mais no Git
      selfHeal: true    # aplica automaticamente mudanças no Git
